#APP SPECIFIC CUSTOM PROPERTIES
app:
  name: spring boot application
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.abc.springbootmicroservice
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    logging:
      enable: true
      url-patterns: "/users/*,/posts/*"
      requestIdParamName: reqId
server:
  port: 8080
logging:
  level:
    root: INFO
    com.abc.demo: DEBUG
  pattern:
    #console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%8.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{REQUEST_ID} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"